services:
    app:
        build: .
        ports:
            - "${PORT:-3000}:${PORT:-3000}"
        env_file:
            - .env
        environment:
            - PORT=${PORT:-3000}
        volumes:
            - ./db:/app/db
        restart: unless-stopped
        networks:
            - local-net

networks:
    local-net:
        name: n8n-local-net
        external: true
